OnTutorDemand/Pages/ChatPages/ChatPage.cshtml.cs
using BusinessObject;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository.RepositoryInterface;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnTutorDemand.Pages.ChatPages
{
    public class ChatPageModel : PageModel
    {
        private readonly IChatMessageRepository chatMessageRepository;
        private readonly IConversationRepository conversationRepository;
        private readonly IAccountRepository accountRepository;

        public ChatPageModel(IChatMessageRepository chatMessageRepository, IConversationRepository conversationRepository, IAccountRepository accountRepository)
        {
            this.chatMessageRepository = chatMessageRepository;
            this.conversationRepository = conversationRepository;
            this.accountRepository = accountRepository;
        }

        [BindProperty]
        public Conversation Conversation { get; set; }

        [BindProperty]
        public List<ChatMessage> ChatMessages { get; set; }

        [BindProperty]
        public List<Conversation> PreviousConversations { get; set; }

        [BindProperty]
        public int UserId { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool IsNew { get; set; } = false;

        [BindProperty]
        public string CurrentUserName { get; set; }

        public string FormatRelativeDate(DateTime dateTime)
        {
            var span = DateTime.Now - dateTime;

            if (span.TotalMinutes < 60)
                return $"{(int)span.TotalMinutes}m";
            if (span.TotalHours < 24)
                return $"{(int)span.TotalHours}h";
            if (span.TotalDays < 7)
                return $"{(int)span.TotalDays}d";
            return $"{(int)(span.TotalDays / 7)}w";
        }

        public async Task<IActionResult> OnGetConversationAsync(int conversationId, bool isNew = false)
        {
            var userEmail = HttpContext.Session.GetString("UserEmail");
            var currentAccount = await accountRepository.GetAccountByEmail(userEmail);
            if (String.IsNullOrEmpty(currentAccount.Email))
            {
                return RedirectToPage("/Authenticate/Login");
            }

            CurrentUserName = currentAccount.FullName;

            UserId = currentAccount.Id;
            PreviousConversations = (await conversationRepository.GetConversationsByUserId(UserId)).ToList();

            Conversation = await conversationRepository.GetConversationById(conversationId);

            if (Conversation == null)
            {
                return RedirectToPage("/ChatPages/ChatPage");
            }
            if (!(Conversation.InitiatorId == UserId || Conversation.ReceiverId == UserId))
            {
                return RedirectToPage("/ChatPages/ChatPage");
            }

            ChatMessages = (await chatMessageRepository.GetChatMessagesByConversationId(conversationId)).ToList();
            IsNew = isNew;
            return Page();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var userEmail = HttpContext.Session.GetString("UserEmail");
            var currentAccount = await accountRepository.GetAccountByEmail(userEmail);
            if (String.IsNullOrEmpty(currentAccount.Email))
            {
                return RedirectToPage("/Authenticate/Login");
            }

            UserId = currentAccount.Id;
            var mostRecentConversation = await conversationRepository.GetMostRecentConversationByAccountId(UserId);

            if (mostRecentConversation != null)
            {
                return RedirectToPage(new { handler = "Conversation", conversationId = mostRecentConversation.Id });
            }
            else
            {
                return Page();
            }
        }
    }
}

OnTutorDemand/Pages/ChatPages/ChatPage.cshtml
@page
@model OnTutorDemand.Pages.ChatPages.ChatPageModel
@{
ViewData["Title"] = "Chat";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Application</title>
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/sb-admin-2/4.1.3/css/sb-admin-2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.9/signalr.min.js"></script>
</head>
<body>
<style>
    .chat-container {
        display: flex;
        height: 80vh;
        background-color: #f8f9fc;
        border: 1px solid #e3e6f0;
        border-radius: .35rem;
    }

    .conversation-list {
        width: 25%;
        border-right: 1px solid #e3e6f0;
        overflow-y: auto;
        background-color: #fff;
        padding: 20px;
    }

    .conversation-item {
        display: flex;
        align-items: center;
        padding: 10px;
        margin-bottom: 10px;
        border-radius: .35rem;
        transition: background-color .2s;
    }

    .conversation-item:hover {
        background-color: #f8f9fc;
    }

    .conversation-item img {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        margin-right: 10px;
    }

    .chat-content {
        width: 75%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        background-color: #fff;
    }

    .chat-header {
        padding: 10px 20px;
        border-bottom: 1px solid #e3e6f0;
        background-color: #f8f9fc;
    }

    .chat-header img {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        margin-right: 10px;
    }

    .chat-header .user-info {
        display: flex;
        align-items: center;
    }

    .message-list {
        flex-grow: 1;
        overflow-y: auto;
        padding: 20px;
    }

    .message-item {
        margin-bottom: 10px;
    }

    .message-input {
        display: flex;
        padding: 10px;
        border-top: 1px solid #e3e6f0;
    }

    .message-input input {
        flex-grow: 1;
        margin-right: 10px;
    }
</style>

<div class="container">
        <input type="hidden" id="isNew" value="@Model.IsNew.ToString().ToLower()" />
    <div class="chat-container">
        <div class="conversation-list">
            <h5>Conversations</h5>
                <ul class="list-unstyled">
                    @if (Model.PreviousConversations == null || !Model.PreviousConversations.Any())
                    {
                        <div id="noConversation">There are no previous conversations.</div>
                    }
                    else
                    {                   
                        @foreach (var conversation in Model.PreviousConversations)
                        {
                            <li class="conversation-item">
                                <img src="/img/undraw_profile_1.svg" alt="User Image" />
                                <a asp-page-handler="conversation" asp-route-conversationid="@conversation.Id">
                                    <div>
                                        @if (conversation.Initiator.FullName.Equals(Model.CurrentUserName))
                                        {
                                            <strong>@conversation.Receiver.FullName</strong><br/>
                                        }
                                        else
                                        {
                                            <strong>@conversation.Initiator.FullName</strong><br/>
                                        }
                                        <small>@Model.FormatRelativeDate(conversation.LastMessageDate)</small><br />
                                    </div>
                                </a>
                            </li>
                        }                  
                    }
                </ul>
        </div>
        <div class="chat-content">
                @if (Model.Conversation == null)
                {
                    <input type="hidden" id="conversationId" value="0" />
                    <input type="hidden" id="userId" value="@Model.UserId" />
                    <div class="chat-header">
                        <p>No conversation selected.</p>
                    </div>
                    <div id="messagesList" class="message-list">
                        <p>Please select a conversation from the list</p>
                    </div>
                }
                else
                {
                    <div class="chat-header">
                        <div class="user-info">
                            <img src="/img/undraw_profile_1.svg" alt="User Image" />
                            <div>
                                @if (@Model.Conversation.Initiator.FullName.Equals(Model.CurrentUserName))
                                {
                                    <strong>@Model.Conversation.Receiver.FullName</strong><br/>
                                }
                                else
                                {
                                    <strong>@Model.Conversation.Initiator.FullName</strong><br/>
                                }
                            </div>
                        </div>
                    </div>
                    <div id="messagesList" class="message-list">
                        @if (Model.ChatMessages == null || !Model.ChatMessages.Any())
                        {
                            <div id="noMessage">There are no messages in this conversation yet.</div>
                        }
                        else
                        {
                            @foreach (var message in Model.ChatMessages)
                            {
                                <div class="message-item">
                                    <strong>@(message.Sender?.FullName ?? "Unknown Sender"):</strong><span>@message.Content</span>
                                </div>
                            }
                        }
                    </div>
                    <div class="message-input">
                        <input type="hidden" id="conversationId" value="@Model.Conversation.Id" />
                        <input type="hidden" id="userId" value="@Model.UserId" />
                        <div class="d-flex flex-column w-100">
                            <textarea id="messageInput" placeholder="Type a message..." class="form-control mb-2"></textarea>
                            <span class="text-danger font-italic font-weight-light" style="font-size: 14px">*Illegal actions or trading sensitive information are prohibited on this platform.</span>
                        </div>
                        <button id="sendButton" class="btn btn-primary ml-2"><i class="fas fa-paper-plane"></i> Send</button>
                    </div>
                }
        </div>
    </div>
</div>
</body>
</html>